[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"
[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/confirmar"
  to = "/.netlify/functions/confirmar"
  status = 200

  [functions]
  node_bundler = "esbuild"
  external_node_modules = ["mysql2"]